apt-packages:
  repositories:
    https://download.docker.com/linux/debian:
      distribution: {{.DebianCodeName}}
      component: stable
    http://packages.cloud.google.com/apt:
      distribution: cloud-sdk-{{.DebianCodeName}}
      component: main
      
  install:
    - apt-transport-https
    - automake
    - build-essential
    - cmake
    - dnsutils
    # TODO(ekg): fix this after adding the repository properly.
    # - docker-ce
    - fonts-inconsolata
    - fonts-go
    - gcc
    - gimp
    - git
    # TODO(ekg): the Google Cloud SDK doesn't work properly; fix the repository.
    - google-cloud-sdk
    - google-cloud-sdk-app-engine-python
    - google-cloud-sdk-datastore-emulator
    - htop
    - i3
    - i3lock
    - id3tool
    - libevent-dev
    - libgit2-dev
    - libncurses5-dev
    - libssl-dev
    - libusb-1.0.0-dev
    - man-db
    - mercurial
    - mosh
    - nmap
    - parallel
    - powertop
    - python3-dev
    - python-dev
    - python-pip
    - rofi
    - sl
    - software-properties-common  # for add-apt-repository
    - ssh
    - strace
    - subversion
    - tmux
    - tree
    - unzip
    - vim-nox  # provides vim with python support
    - weechat-curses
    - xbacklight
    - xfce4-power-manager
    - xfce4-pulseaudio-plugin
    # TODO(ekg): this takes forever to install. why?
    # - xserver-xorg-input-synaptics
    - xss-lock
    - zip
    - zsh
  remove:
    - command-not-found

git-repositories:
  https://github.com/gmarik/Vundle.vim.git:       ~/.vim/bundle/Vundle.vim
  https://github.com/robbyrussell/oh-my-zsh.git:  ~/.oh-my-zsh
  https://github.com/minusnine/ericgar.com.git:   ~/src/ericgar.com
  https://github.com/tmux-plugins/tpm:            ~/.tmux/plugins/tpm
  https://go.googlesource.com/go:                 ~/src/go
  https://github.com/myusuf3/numbers.vim.git:     ~/.vim/bundle/numbers
  https://github.com/vim-syntastic/syntastic.git: ~/.vim/bundle/syntastic
  https://github.com/tmux/tmux.git:               ~/src/tmux

go-packages:
  - github.com/tebeka/selenium
  - github.com/pkg/sftp
  - github.com/spf13/hugo
  - golang.org/x/tools/cmd/goimports
  - golang.org/x/sync/errgroup

directories:
  create:
    - ~/.vim
    - ~/.vim/autoload
    - ~/tmp
    - ~/tmp/vim
    - ~/.ssh
    - ~/src
    - ~/bin
    - ~/.urxvt
    - ~/.urxvt/ext
    - ~/opt
  remove:
    - ~/Desktop
    - ~/Documents
    - ~/Downloads
    - ~/Music
    - ~/Pictures
    - ~/Public
    - ~/Templates
    - ~/Videos

groups: 
  - docker
